version: '3.9'

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - DB_PASSWORD=pw
      - DB_USER=user
      - DB_NAME=db
